import { Modal, App } from 'obsidian';
import { Html5Qrcode } from 'html5-qrcode';

export class QrScannerModal extends Modal {
    private html5QrcodeScanner: Html5Qrcode | null = null;

    constructor(app: App, private onScanSuccess: (decodedText: string) => void) {
        super(app);
    }

    onOpen() {
        const { contentEl } = this;
        contentEl.empty();
        contentEl.createEl('h2', { text: 'Scan Network QR Code' });
        contentEl.createEl('p', { text: 'Align the QR Code generated by your other device within the camera frame below.' });

        const readerDiv = contentEl.createDiv({ id: 'crdt-sync-reader' });

        // Instantiate scanner after DOM render
        setTimeout(() => {
            try {
                this.html5QrcodeScanner = new Html5Qrcode('crdt-sync-reader');
                this.html5QrcodeScanner.start(
                    { facingMode: 'environment' },
                    {
                        fps: 10,
                        qrbox: { width: 250, height: 250 }
                    },
                    (decodedText) => {
                        this.onScanSuccess(decodedText);
                        this.close();
                    },
                    (errorMessage) => {
                        // ignore or handle scanner verbosely
                    }
                ).catch((err) => {
                    console.error('Failed to start scanner:', err);
                    readerDiv.createEl('p', { text: 'Could not access camera. Please make sure you granted camera permissions.' });
                });
            } catch (err) {
                console.error(err);
                readerDiv.createEl('p', { text: 'Failed to initialize scanner. Make sure camera access is supported.' });
            }
        }, 100);
    }

    onClose() {
        if (this.html5QrcodeScanner) {
            this.html5QrcodeScanner.stop().catch((err) => console.error('Error stopping scanner:', err));
        }
        const { contentEl } = this;
        contentEl.empty();
    }
}
